SpringSecurity 세팅
FC-BE-ToyProject-Team8/TravelApp pull request #104
Opened 2023-11-12 10:12 UTC by cyPark95

## 개요

close #60 

Spring Security 기본 세팅입니다.

- JWT Provider 클래스에서 JWT 관련 기능 구현
- Security Config 클래스에서 시큐리티 설정
- Security Filter를 만들어서 UsernamePasswordAuthenticationFilter 전에 검증
- 401, 403에 대한 예외 핸들러 기본 설정

현재는 로그인, 회원가입 기능 구현 전으로 통합테스트가 실패하는 상태입니다.
로그인, 회원가입 구현 후, 코드 병합을 통해 해결할 수 있도록 하겠습니다

## 협의 필요
  - 인증/인가 예외가 발생하면, 현재 401, 403 HttpStatus만 반환하고 있고, 반환 내용에 대한 협의가 필요합니다.
  - Security Context에 포함할 사용자 정보에 대한 협의가 필요합니다.

## PR 유형
어떤 변경 사항이 있나요?
- [x] 새로운 기능 추가
- [  ] 버그 수정
- [  ] CSS 등 사용자 UI 디자인 변경
- [  ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [  ] 코드 리팩토링
- [  ] 주석 추가 및 수정
- [  ] 문서 수정
- [  ] 테스트 추가, 테스트 리팩토링
- [  ] 빌드 부분 혹은 패키지 매니저 수정
- [  ] 파일 혹은 폴더명 수정
- [  ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [  ] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [  ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

2023-11-13 06:30 UTC, deepredk requested changes
인증/인가 예외가 발생하면, 현재 401, 403 HttpStatus만 반환하고 있고, 반환 내용에 대한 협의가 필요합니다.
=> 둘 모두 FAIL, 로그인이 필요합니다 정도면 될 것 같습니다

Security Context에 포함할 사용자 정보에 대한 협의가 필요합니다.
=> 이메일만 있으면 될 것 같습니다

빌드 실패인 채 Merge되면 이후 작업자들이 계속 빌드 실패인채로 Merge 해야하는 부분이 있어서 Request changes로 submit 해둡니다!

2023-11-13 06:39 UTC, cyPark95 commented
@deepredk 401에 대해서 토큰 만료된 상태 구분이 필요합니다.
로그인 부분이 완료한 후에 Merge 해소하도록 하겠습니다!

2023-11-13 07:32 UTC, deepredk commented
@cyPark95 
아 401은 토큰 만료였나요? 그러면 토큰이 만료되었습니다. /reissue를 통해 재발급 받아주세요. 정도면 될 것 같슴다

2023-11-14 01:24 UTC, hyeond0 approved these changes
고생하셨습니다 :)

2023-11-14 01:28 UTC, windowM approved these changes

2023-11-14 01:31 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfig.java
> +        return http.build();
스프링 시큐리티6, 부트3 자바17에 맞게 .authorizeRequests()가 .authorizeHttpRequests()로 바뀌었고  .antMatchers() 메소드가 사라지고 .requestMatchers() 로 변경 된 점 반영된 건 잘 봤습니다. 혹시 .build() 대신 .getOrBuild()를 쓰라고 공부했는데, 어떻게 생각하시나융?

2023-11-14 01:35 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/travel/common/secure/domain/JwtProvider.java
> +        byte[] secretByteKey = Decoders.BASE64.decode(secretKey);
String base64EncodedSecretKey = Base64.getEncoder().encodeToString(secretKey.getBytes());
byte[] keyBytes = Decoders.BASE64.decode(base64EncodedSecretKey);
로 안 쓰고 위 에 작성하신 한문장으로도 가능한가용?!

2023-11-14 01:36 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/travel/domain/member/entity/RoleType.java
> +}
} 다음 줄에 빈 줄 하나 없어도 되나요?

2023-11-14 01:36 UTC, Programmer-may approved these changes
고생하셨습니다! 이야기 나눠볼 거리 적어 봤습니당!!!

2023-11-14 01:42 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/common/secure/domain/JwtProvider.java
> +        byte[] secretByteKey = Decoders.BASE64.decode(secretKey);
String base64EncodedSecretKey = Base64.getEncoder().encodeToString(secretKey.getBytes());
String을 base64로 인코딩 하는 로직인것 같은데...
제가 인코딩된 문자열을 yml에 추가시켜놔서 안했습니다.

여기서 인코딩하는 방식도 괜찮아보이네요!
말씀처럼 수정하겠습니다!

2023-11-14 01:43 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/member/entity/RoleType.java
> +}
오! 그렇네요.
추가하겠습니다!

근데 왜 깃허브에서 x표시 안해주는지 모르겠네요...?🤔

2023-11-14 01:44 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/common/secure/config/SecurityConfig.java
> +        return http.build();
getOrBuild를 처음봐서 어떤 차이가 있나요?

2023-11-14 05:49 UTC, deepredk approved these changes
고생하셨습니다

2023-11-14 05:50 UTC, merged