feature/100 사용자 닉네임으로 여행 찾기 기능 구현
FC-BE-ToyProject-Team8/TravelApp pull request #110
Opened 2023-11-13 16:25 UTC by Programmer-may

## 개요
사용자 닉네임으로 여행 찾기 기능 구현
컨트롤러, 서비스, 레포지토리 각 계층 마다 맞는 메소드 구현하였고,
MemberRepository 에서 닉네임으로 Member 찾는 메소드 또한 구현하였습니다.
사용자 닉네임으로 여행 찾기 서비스계층에서 성공 및 실패 테스트 코드 작성,
사용자 닉네임으로 여행 찾기 컨트롤러 계층 테스트 코드 작성하였습니다.

## PR 유형
어떤 변경 사항이 있나요?
- [x] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [x] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [x] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [x] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [x] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

2023-11-14 01:38 UTC, cyPark95 approved these changes
테스트 코드까지 너무 고생하셨습니다. 👍🏻

몇 가지 코멘트 남겨놨습니다!

2023-11-14 01:38 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
> +    private final MemberRepository memberRepository;
TripService와 memberService를 의존하는건 어떨까요?🤔

2023-11-14 01:38 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
> +        if (likeRepository.existsByTripAndMemberId(trip, memberId)) {
메서드로 분리하면 가독성도 좋아지고 나중에 재활용할 수 있을것 같아요!

2023-11-14 01:38 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
> +            .build();
메서드로 분리하면 좋을 것 같습니다!

2023-11-14 01:38 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
> +    }
아직 구현 안하신거 같긴 한데... 좋아요 수를 수정하는 메서드일까요?

2023-11-14 01:38 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
> +        @RequestParam(required = false, defaultValue = "1", value = "page") int page) {
객체로 만들어서 ModelAtrribute를 사용해보는건 어떨까요?

2023-11-14 01:38 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/trip/repository/TripRepository.java
> +    List<Trip> findTripByMember(Member member, PageRequest pageRequest);
Page가 아닌 List로 반환하는 이유가 있나요?

2023-11-14 01:38 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
> +        @RequestParam(required = false, defaultValue = "1", value = "page") int page) {
그게 아니라면 추가로 스프링은 Pageable을 사용해보시는건 어떤가요?

2023-11-14 01:56 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
> +        @RequestParam(required = false, defaultValue = "1", value = "page") int page) {
Pageable 이용한 pageRequest 를 사용해 보았습니다

2023-11-14 01:58 UTC, Programmer-may commented on src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
> +    private final MemberRepository memberRepository;
@cyPark95 아래에서 말씀해주신 좋아요 관련된 내용들 다 전 내용들이라 지금은 따로 되어 있습니다!! ㅠㅠㅠ 이 부분만 참고해서 수정하겠습니다!!!!

2023-11-14 02:05 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/like/service/LikeService.java
> +    private final MemberRepository memberRepository;
아하! 그렇네요..

2023-11-14 02:07 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
> +        @RequestParam(required = false, defaultValue = "1", value = "page") int page) {
파라미터로 Pageable을 받을 수 있어요!
[Pageable ](https://tecoble.techcourse.co.kr/post/2021-08-15-pageable/) 참고해보시고 좋은 방법을 선택해보시면 좋을 것같아요!

2023-11-14 04:39 UTC, deepredk commented on src/main/java/kr/co/fastcampus/travel/domain/trip/controller/TripController.java
> +        @RequestParam(required = false, defaultValue = "1", value = "page") int page) {
https://velog.io/@mooh2jj/SpringBoot-Paging-처리-방법
이렇게 List 대신 Page 반환할 수 있고 이게 정석인 것 같습니다 (저도 Page 관련은 해본적이 없어서 이렇게 했을때 반환형태가 원하는대로 잘 나오는지는 확신하지 못하겠습니다)

2023-11-14 05:23 UTC, deepredk requested changes
Pageable 관련해 수정이 필요할거같아 전 Request changes로 남겨두겠습니다

2023-11-15 02:52 UTC, deepredk approved these changes
고생하셨습니다!

2023-11-15 07:30 UTC, hyeond0 approved these changes
고생하셨습니다 :)
Pageable을 사용해서 controller에서 반환할 때 
페이지에 관한 정보도 같이 들어가야 한다고 생각하는데 어떻게 생각하세요?

2023-11-15 07:33 UTC, windowM approved these changes
고생하셨습니다~👍

2023-11-15 07:37 UTC, Programmer-may commented
@hyeond0 머지하고 추후에 브랜치 파서 현도님처럼 통일하든가 해야겠네용~!!

2023-11-15 07:48 UTC, merged