댓글 작성 기능 구현
FC-BE-ToyProject-Team8/TravelApp pull request #111
Opened 2023-11-13 18:14 UTC by windowM

## 개요
controller/service DTO분리가  되면서 굉장히 헷갈리네요..ㅠ😭 
거기에 유저가 들어오면서 도저히 방향을 잡지 못하겠어서 질문먼저 올리겠습니다ㅠ

- 댓글 추가 요청을 처리하기 위한 유저 정보 입력(?)은 어떤식으로 이뤄져야 하는지 잘 이해가 안갑니다.  
(단순 사용자에게 요청 받는 방식이 아니기에.../ 주현님 코드를 보니 Principal을 사용하긴 하던데... 질문남깁니다....)
+ 댓글 추가시 사용자에게 요청받는 request에는 content(메시지 내용)만 받는게 맞을까요?

-  찬영님께 드리는 질문인데,  댓글을 추가하기 위해 trip/ member  정보를 단순 조회해야 하는 로직이 들어가는데, 
어떤식으로 묶어서 진행해야 할지 모르겠습니다... 
(질문이 다소 모호한데, 어제 질문드린 내용과 관련된 내용에서의 고민입니다. 내일 다시 여쭤보겠습니다ㅠ)

🙌 도움이 많이 필요할 것 같습니다...ㅠ 최대한 빨리 수용해서 진도 맞추겠습니다!

## PR 유형
어떤 변경 사항이 있나요?
- [ ] 새로운 기능 추가
- [ ] 버그 수정
- [ ] CSS 등 사용자 UI 디자인 변경
- [ ] 코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)
- [ ] 코드 리팩토링
- [ ] 주석 추가 및 수정
- [ ] 문서 수정
- [ ] 테스트 추가, 테스트 리팩토링
- [ ] 빌드 부분 혹은 패키지 매니저 수정
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

2023-11-14 01:54 UTC, cyPark95 approved these changes
고생하셨습니다!

reviewdog에 많이 걸리셨네요...😢
저도 습관이 안돼 있어서 힘들지만 코드 완성하구 `컨트롤` +`알트` +`L` 해주시면 많이 걸러질 수 있을 것 같아요!!

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/comment/controller/CommentController.java
> +    @PostMapping("")
매핑될 url이 없다면 괄호 자체를 지워주시는게 더 깔끔해 보일것 같아요!

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/comment/controller/CommentController.java
> +        return ResponseBody.ok(mapper.of(response));    // commentInfoDto -> commentResponse
불필요한 주석은 없는게 좋은것 같아요!

인테페이스 명은 DtoMapper지만 제가 변수명을 mapper라고 해서 의미가 명확하지 않으셨다면 dtoMapper로 변경하셔도 될 것 같아요!

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/comment/controller/dto/response/CommentResponse.java
> +) {
불필요한 개행이 있는것 같아요!!

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/comment/entity/Comment.java
> +    }
코멘트 내용만 수정하는거라면 String을 파라미터로 받는건 어떨까요?

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/comment/service/CommentService.java
> +    private final TripRepository tripRepository;
TripService를 주입받는건 어떤가요?🤔

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/comment/service/dto/request/CommentSaveDto.java
> +    public Comment toEntity() {
불필요한 개행이 있는것 같아요!

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/member/entity/Member.java
> +    private List<Comment> comments = new ArrayList<>();
양방향 연관관계는 필수가 아니라고 생각하는데,
멤버를 조회할 때, 코멘트가 필요할 일이 있을까요?🤔

2023-11-14 01:54 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/member/service/dto/request/MemberSaveDto.java
> +
불필요한 개행인것 같습니다!

2023-11-14 04:32 UTC, deepredk commented
댓글 추가 요청을 처리하기 위한 유저 정보 입력(?)은 어떤식으로 이뤄져야 하는지 잘 이해가 안갑니다.
(단순 사용자에게 요청 받는 방식이 아니기에.../ 주현님 코드를 보니 Principal을 사용하긴 하던데... 질문남깁니다....)
=> Spring Security 코드가 아직 구현되지 않아 임시로 짜야 합니다. request에서 임시로 userId 등을 받는 방법 등을 생각할 수 있을 것 같습니다

댓글 추가시 사용자에게 요청받는 request에는 content(메시지 내용)만 받는게 맞을까요?
=> 네

2023-11-14 05:09 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/domain/comment/controller/CommentController.java
> +        return ResponseBody.ok(mapper.of(response));    // commentInfoDto -> commentResponse
개행 및 주석 관련된건은 기능 완성을 못시켜서 아직 정리하지 않았습니다ㅠ

2023-11-14 05:09 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/domain/comment/entity/Comment.java
> +    }
넴 content만 사용해도 되는게 맞는거 같아서 바꿔놓도록 하겠습니다!

2023-11-14 05:10 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/domain/comment/service/CommentService.java
> +    private final TripRepository tripRepository;
혹시 어떤 말씀이시죠?

2023-11-14 05:11 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/comment/service/CommentService.java
> +    private final TripRepository tripRepository;
지금은 TripReposiroy를 주입받고 있는데 TripService를 주입받는건 어떤가요?

2023-11-14 05:11 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/domain/member/entity/Member.java
> +    private List<Comment> comments = new ArrayList<>();
자신이 남긴 댓글들을 모두 조회 할 경우가 생기지 않을까 싶어 
혹시 넣어놔야 하나 싶었습니다!

2023-11-14 05:12 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/domain/member/entity/Member.java
> +    private List<Comment> comments = new ArrayList<>();
그런 경우에는 Comment에서 Member를 통해 조회해도 좋을 것 같아요!

2023-11-14 05:51 UTC, deepredk requested changes
build, checkstyle 실패하고 있는 관계로 Request changes 해두겠습니다

2023-11-14 14:05 UTC, deepredk commented on src/main/java/kr/co/fastcampus/travel/domain/comment/controller/dto/response/CommentResponse.java
> +            .trip(getTrip(comment.getTrip()))
요거는 메서드 분리 안하는 편이 더 직관적일 것 같습니다!

Member을 입력받아 MemberResponse를 반환하는 getMember라는 이름의 함수가 뭘 하는걸까?가 예상이 되지 않아 직관성이 떨어져서 메서드 이름 변경 등이 필요할 것 같은데
이 정도 코드라면 아예 inline이나 지역변수 선언하는 정도가 좋을 것 같습니다

2023-11-14 14:06 UTC, deepredk commented on src/main/java/kr/co/fastcampus/travel/domain/comment/entity/Comment.java
> +    }
add보다는 set이 적절할 것 같습니다

2023-11-14 17:48 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/domain/comment/entity/Comment.java
> +    }
저도 넣고 보니 set이 더 좋을 거 같다 생각했습니다.😀
수정해놓겠습니다!

2023-11-15 06:10 UTC, deepredk approved these changes
컨트롤러 테스트는 Spring Security 적용 이슈에서 추가해도 괜찮을 것 같아 Approve 해둡니다!

2023-11-15 07:32 UTC, hyeond0 approved these changes
고생하셨습니다!
각 기능에 대해 실패와 성공 케이스 테스트하는 것 너무 좋네요 :)

2023-11-15 09:22 UTC, Programmer-may approved these changes
빌드가 실패가 뜨네요 ㅜㅜ 일단 approve 드리겠습니다!

2023-11-15 09:42 UTC, merged