feat : 여정 수정 Spring Security 적용
FC-BE-ToyProject-Team8/TravelApp pull request #131
Opened 2023-11-15 12:33 UTC by windowM

closes #76 
## 개요
- 여정 수정시 여행을 등록한 사람이 여정을 수정할 수 있다.

## PR 유형
어떤 변경 사항이 있나요?
- [ ] 새로운 기능 추가
- [ ] 테스트 추가, 테스트 리팩토링

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.
- [ ] 커밋 메시지 컨벤션에 맞게 작성했습니다.  Commit message convention 참고  (Ctrl + 클릭하세요.)
- [ ] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트)

2023-11-15 12:50 UTC, deepredk requested changes
여정 수정쪽 컨트롤러 테스트가 구현되지 않은 것 같슴다

2023-11-16 00:56 UTC, deepredk commented on src/test/java/kr/co/fastcampus/travel/domain/itinerary/controller/ItineraryControllerTest.java
> -//package kr.co.fastcampus.travel.domain.itinerary.controller;
이거 아예 삭제하는건.. 다른분들 기존 코드 복붙을 못할 것 같습니다

2023-11-16 00:56 UTC, deepredk commented on src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerGetTripTest.java
> +    void findAll() {
여행 목록 컨트롤러 테스트를 요기 PR에서 작업하시네요??
여행 목록의 경우 비회원도 되게끔하는게 자연스러운 것 같습니다 (permitAll)

2023-11-16 01:04 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/domain/itinerary/controller/ItineraryControllerTest.java
> -//package kr.co.fastcampus.travel.domain.itinerary.controller;
아 itinerarycontroller를 다시 만들었는데 push되지 않았네요. 다시 올리겠습니다!

2023-11-16 01:06 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/domain/trip/controller/TripControllerGetTripTest.java
> +    void findAll() {
아닙니더 아마 머지하는 과정에서 땡겨와진거 같아요...

2023-11-16 01:25 UTC, deepredk approved these changes

2023-11-16 01:38 UTC, merged