Feature/13
FC-BE-ToyProject-Team8/TravelApp pull request #30
Opened 2023-10-25 14:51 UTC by windowM

closes #13
- 여정을 수정하는 기능입니다. ( PUT / Itineraries/{id} ) 
- 여정 요청을 위한 Lodge,Stay,Route Request DTO 생성
- 여정 request DTO -> 여정 Entity로 변환하는 메소드 추가
`toItinerary()`, `toLodge()`, `toStay()`, `toRoute()` 
- 예외처리 진행
  - 여정이 존재하지 않는다면, `EntityNotFoundException` 발생
  - 추가 예외 & 유효성 검사 처리는 아직 진행하지 않음.
   필요한 사항들 말씀 부탁드립니다! 
   ( 날짜 형식 검사 추가 예정)

👉 전체적으로 진홍님의 여행 수정 코드를 많이 참고하였습니다!

2023-10-25 14:53 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/controller/request/ItineraryRequest.java
> +
지워두었습니다!

2023-10-26 05:48 UTC, deepredk requested changes
고생하셨습니다!

남긴 피드백은 아래와 같습니다
1. Lodge, Route, Stay 정보를 모두 넣어야만 수정이 되는 문제점을 말씀드린 것 (이건 필히 수정되어야 한다고 생각합니다)
2. Test를 위한 Entity를 만드는 메서드를 따로 분리해내는 것을 권장드린 것
3. 그 외 가독성 등 기타

2023-10-26 05:48 UTC, deepredk commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +    @DisplayName("여행과 여정 조회")
`@DisplayName`쪽 오타 있는 것 같습니다!

2023-10-26 05:48 UTC, deepredk commented on src/main/java/kr/co/fastcampus/travel/controller/request/ItineraryRequest.java
> +    StayRequest stay
혹시 이렇게 했을 때
기존에는 Route, Lodge, Stay 모두 저장돼있었는데
Stay 하나만 존재하도록 수정하는 거 막히거나 하진 않나요?

2023-10-26 05:48 UTC, deepredk commented on src/main/java/kr/co/fastcampus/travel/controller/util/TravelDtoConverter.java
> +            .build();
DtoConverter쪽 코드 ~~Request에 대한 null 관련 처리가 없는걸 보니까 명확해지네요 

지금 코드대로라면
사용자가 처음에 등록할 때 Route 하나만 등록했더라도
'수정'을 할 떄는 Route, Lodge, Stay 모두를 입력해야만 수정이 가능할 것 같습니다

2023-10-26 05:48 UTC, deepredk commented on src/main/java/kr/co/fastcampus/travel/service/ItineraryService.java
> +
이쪽 줄바꿈은 제거해주세요!

2023-10-26 05:48 UTC, deepredk commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +            .build();
여정 관련 Entity 만드는 코드가 이렇게 굉장히 길어진다면 메서드 분리 하면 더 좋을 것 같습니다
현도님 코드 참고하셔서 분리해보시는건 어떨까요?

2023-10-26 05:48 UTC, deepredk commented on src/test/java/kr/co/fastcampus/travel/service/ItineraryServiceTest.java
> +        //given
//와 given, when, then 사이에 띄어쓰기 해주세요!

2023-10-26 05:56 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +    @DisplayName("여행과 여정 조회")
확인하였습니다!

2023-10-26 06:08 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/controller/util/TravelDtoConverter.java
> +            .build();
엇 null 처리 부분은 오늘 오전 주현님이 슬래에 올려주신 것 보고 깨닳아서 수정해두었습니다!
감사합니다~

2023-10-26 06:09 UTC, deepredk commented on src/main/java/kr/co/fastcampus/travel/controller/util/TravelDtoConverter.java
> +            .build();
@windowM 넵 셋 중 아무거나 하나만으로 수정되는 테스트도 하나 있으면 좋을 것 같습니다!

2023-10-26 06:10 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +            .build();
현도님, 주현님 코드 확인하였습니다~ 정리되면 수정하도록 하겠습니다!

2023-10-26 07:14 UTC, hyeond0 approved these changes
고생하셨습니다!
여정 정보 하나하나 꼼꼼히 입력해서 테스트해주셨네요 👍

2023-10-26 07:14 UTC, hyeond0 commented on src/main/java/kr/co/fastcampus/travel/service/ItineraryService.java
> +            itineraryRepository.findById(id).orElseThrow(EntityNotFoundException::new);
제 리뷰에서도 말씀주셨다시피 findById 분리하면 좋을 것 같습니다 :)

2023-10-26 07:31 UTC, Programmer-may approved these changes

2023-10-26 07:33 UTC, Programmer-may commented
여정 수정 하나하나 확인하려고 값 넣는라 고생하셨습니다. 가짜 객체 만드는 건 유틸리티 클래스에서 static 메소드로 만들어서 호출하여 사용하면 깔끔할 거 같습니다. 지금 현도님 유틸이랑 제 유틸이랑 둘다 있어서 합쳐야하는데, 현도님껄 제가 제껄로 합쳤는데 이번에 삭제 pr에 또 그래도 있어서 수정해야할거 같더라구요. 창호님도 한 곳 정해서 넣으시면 될거같습니다

2023-10-26 13:41 UTC, cyPark95 approved these changes
꼼꼼한 테스트 너무 좋네요!! 고생하셨습니다.

추가로 궁금한점이나 의견은 코멘트 남겨놨습니다!

2023-10-26 13:41 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/service/ItineraryService.java
> +    }
데이터 수정이 없는 Transactional의 옵션을 readOnly=true로 설정하면 이점이 많아요!

2023-10-26 13:41 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +    }
만들고 있는 객체는 모의 객체가 아닌데.. 왜 메서드에 Mock이라는 단어가 있는지 궁금합니다! 🤔

2023-10-26 13:41 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +        Itinerary itinerary = createMockItinerary(trip, route, lodge, stay);
route, lodge, stay를 생성하고, 파라미터로 trip을 전달받아서 itinerary를 생성하는 create 메서드를 만들어보면 어떨까요?

2023-10-26 13:41 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +            .build();
dto가 아니라 엔티티를 파라미터로 전달받았는데, null 체크가 필요할까요...?

2023-10-26 13:41 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +    }
Url을 파라미터로 전달받는다면 다른 메서드를 테스트할 때도 재활용할 수 있을 것 같아요!

2023-10-26 13:41 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +        });
꼼꼼한 테스트 너무 좋네요! 👍

2023-10-26 13:53 UTC, windowM commented on src/main/java/kr/co/fastcampus/travel/service/ItineraryService.java
> +    }
찾아보고 수정해 놓도록 하겠습니다!

2023-10-26 15:31 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +        Itinerary itinerary = createMockItinerary(trip, route, lodge, stay);
이해했습니다! 추가하도록 하겠습니다.

2023-10-26 15:34 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +            .build();
그렇네요😨 DTO대신 Entity를 받는것 까진 문제가 없을까요?

2023-10-26 15:41 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +    }
여정 수정 부분에서는 사용되지 않는 메소드라 냅두겠습니다!
대신 Line 38~49 한번 확인부탁드려도 될까요? 
( 메소드명 & url 여부 )

2023-10-26 17:13 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +    }
Mock이 가지는 의미가 가짜 객체를 생성한다는것 까진 알겠는데...
임의의 데이터를 넣는 부분에서 같은 맥락인줄 알았습니다...
mock을 제거하고 createStayRequest로 가져가면 문제 없을까요?

2023-10-26 23:34 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +    }
제가 생각은 그러하지만... 정답이 아니라서 고민이 되긴 하네요!

2023-10-26 23:35 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +        Itinerary itinerary = createMockItinerary(trip, route, lodge, stay);
제가 생각한건 창호님이 작성해주신게 맞긴 해요!
메소드 분리를 통해서 결과적으로 원하는 Itinerary만 생성한다는 의미의 메서드를 만들면 어떨까요? 라는 말이였어요!

2023-10-26 23:36 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/TestUtil.java
> +            .build();
해당 메서드는 엔티티를 만들기 위한 메서드라서 엔티티를 받는건 문제가 없을것 같은데요?

2023-10-27 01:03 UTC, deepredk approved these changes

2023-10-27 02:09 UTC, cyPark95 approved these changes
리뷰 반영해 주시느라 고생하셨습니다.

추가로 몇가지 코멘트 추가해 봤습니다!

2023-10-27 02:09 UTC, cyPark95 commented on src/main/java/kr/co/fastcampus/travel/service/ItineraryService.java
> +    @Transactional(readOnly = true)
클래스 래벨로 설정하는건 어떨까요?

여정은... 조회 로직이 많은지 그 외 로직들이 많을지 잘 판단이 안되긴 하지만
Transactional 설정을 클래스 래벨로 설정하면 해당 설정에 대해서는 메서드 레벨에서 설정하지 않아도 돼서 편할 것 같아요!

2023-10-27 02:09 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/TravelTestUtils.java
> +        Stay stay = createStay();   // stay 생성
충분히 메서드명을 통해 의미전달이 되고있는 것 같아요 👍
불필요한 주석은 없는게 좋은것 같습니다!

2023-10-27 02:09 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +        ItineraryRequest request = createItineraryRequest(route2, lodge2, stay2);
변수명도 이제는 lodge2 -> lodge로 변경해도 되지 않을까요?

2023-10-27 02:09 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/service/ItineraryServiceTest.java
> +        StayRequest stay2 = createStayRequest();
위와 같은 내용인것 같습니다!

2023-10-27 02:09 UTC, cyPark95 commented on src/test/java/kr/co/fastcampus/travel/service/TripServiceTest.java
>          trips.add(trip2);
stream을 사용해보면 어떨까요?

2023-10-27 02:52 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/service/TripServiceTest.java
>          trips.add(trip2);
요건 현도님이 작성해주신 코드입니당!

2023-10-27 02:52 UTC, windowM commented on src/test/java/kr/co/fastcampus/travel/controller/TravelControllerTest.java
> +        ItineraryRequest request = createItineraryRequest(route2, lodge2, stay2);
넵!
Request만큼은 한번에 만들어주는 메소드를 따로 정의하지 않았습니다!

2023-10-27 03:15 UTC, merged

2023-10-27 06:28 UTC, deepredk reviewed
확인했습니다 리뷰 사항 없습니다!